### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by devinfoley** [acrosa/scala-redis#10]
Is this driver threadsafe? Can I safely access an instance of RedisClient from multiple Actors? I seem to be getting deadlocks immediately after executing a method on RedisClient. I'm a bit new to Scala so forgive me if this is a bad question.

**Comment by acrosa** [comment]
The library is not Thread safe, you should have an instance of RedisClient (the object it's quite small) per Thread.
As a side note, I don't think it's a good idea to call concurrently an ext. library that performs IO from your actors. Actors are good fit for cpu bound tasks and immutable/idempotent stuff _in my opinion_. :)
