### ISSUE TITLE
get fails to return the expected value

### ISSUE THREAD

**Issue by bhickey** [acrosa/scala-redis#4]
```
import com.redis._;

object GetFailsTest extends Application {

  val r = new Redis("localhost", 6379)
  r.set("key", "some value")
  println(r.get("key"))
  println(r.get("key").get)
}
```

I believe that this code should print: 
    Some("some value")
    "some value"
Instead it prints: 
    None
    10

I've compiled with scala-2.7.7 and am running against Redis 2.2.0.

**Comment by acrosa** [comment]
Works for me, since "key" is being set, why it should return None?

scala> import com.redis._;
import com.redis._

scala> object GetFailsTest extends Application {
     | 
     |   val r = new Redis("localhost", 6379)
     |   r.set("key", "some value")
     |   println(r.get("key"))
     |   println(r.get("key").get)
     | }
defined module GetFailsTest

scala> GetFailsTest.main(Array(""))
Some(some value)
some value
